# produto1=str (input('Digite o nome do produto 1:'))
# valor1=float (input('Digite o valor do produto1:'))
# produto2=str (input('Digite o nome do produto 2:'))
# valor2=float (input('Digite o valor do produto 2:'))
# produto3=str (input('Digite o nome do produto 3:'))
# valor3=float (input('Digite o valor do produto 3:'))
produto1="AHUOAsoASijOIASjoisjoj "
valor1=float (10)
produto2=str ("Asasda")
valor3=float (1)
produto3=str ('Digite o nome do produto 3:')
valor2=float (1500)

print('_'*25)
print('|{:^23}|'.format('C U P O M F I S C A L'))
print('|{:>24}'.format ('|'))
print('| {:<22}|'.format('PRODUTO #1'))
print('| {:<12.12} R${:<7.2f}|'.format (produto1, valor1))
print('|{:>24}'.format ('|'))
print('| {:<22}|'.format('PRODUTO #2'))
print('| {:<12.12} R${:<7.2f}|'.format (produto2, valor2))
print('|{:>24}'.format ('|'))
print('| {:<22}|'.format('PRODUTO #3'))
print('| {:<12.12} R${:<7.2f}|'.format (produto3, valor3))
print('|{:>24}'.format('|'))
print('|TOTAL:{:<5.5} R${:>8.2f} |'.format('',valor1+valor2+valor3))
print('_'*25)